### ISSUE TITLE
Error in apache configuration for lazy authentication

### ISSUE THREAD

**Issue by aptiko** [aduitsis/ntua-docker-lamp-shibboleth#1]
In the last block:

```
<Location /lazy>
    AuthType shibboleth
    ShibRequireSession Off
    Require Shibboleth
</Location>
```

`Require Shibboleth` should be `Require shibboleth`, with a lower-case `s`.

In addition, `ShibRequireSession Off` should be `ShibRequestSetting requireSession 1` (for consistency with the previous block, and because `ShibRequireSession` is deprecated), but it also works without it, and I think the preferred way is without it (unless the location is a sublocation of a location where a session is required).

**Comment by aduitsis** [comment]
Thanks!

Would you like to issue a pull request so that I can accept it? Or should I just make the corrections myself?

**Comment by aptiko** [comment]
Given that the issue is about lazy stuff, I'll take the option of being lazy :-)
